import Navbar from './components/Navbar'
import './globals.css'
import { Inter,Roboto } from 'next/font/google'

const inter = Roboto({ subsets: ['latin'],weight:['400','700'] })

export const metadata = {
  title: 'My Portfilio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=''>
      <body className={inter.className }>
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
